name: Sync from FEF Template Repo

on:
  # 1. Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # 2. Runs on a schedule (the 1st of the month and the 23rd to pick up any changes)
  # TODO: enable once the workflow works
  #schedule:
  #- cron: '0 3 1,23 * *'

jobs:
  sync:
    uses: uc-cdis/.github/.github/workflows/gen3_Sync_FeF.yaml@paulineribeyre-patch-1
